<?php

use Illuminate\Database\Seeder;
use Modules\Usermanagement\Entities\County;
use Modules\Usermanagement\Entities\SubCounty;

class SubCountySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    public function run()
    {
         $sub_counties = array(
  array('id' => '1','name' => 'Uasin Gishu','subcounty_name' => 'AINABKOI '),
  array('id' => '2','name' => 'Machakos','subcounty_name' => 'ATHI RIVER'),
  array('id' => '3','name' => 'Migori','subcounty_name' => 'Awendo'),
  array('id' => '4','name' => 'Mandera','subcounty_name' => 'Banisa'),
  array('id' => '5','name' => 'Baringo','subcounty_name' => 'BARINGO'),
  array('id' => '6','name' => 'Kericho','subcounty_name' => 'BELGUT'),
  array('id' => '7','name' => 'Bomet','subcounty_name' => 'BOMET '),
  array('id' => '8','name' => 'Bomet','subcounty_name' => 'BOMET EAST'),
  array('id' => '9','name' => 'Siaya','subcounty_name' => 'Bondo'),
  array('id' => '10','name' => 'Nyamira','subcounty_name' => 'Borabu'),
  array('id' => '11','name' => 'Bungoma','subcounty_name' => 'BUMULA'),
  array('id' => '12','name' => 'Wajir','subcounty_name' => 'BUNA'),
  array('id' => '13','name' => 'Bungoma','subcounty_name' => 'BUNGOMA CENTRAL'),
  array('id' => '14','name' => 'Bungoma','subcounty_name' => 'BUNGOMA EAST'),
  array('id' => '15','name' => 'Bungoma','subcounty_name' => 'BUNGOMA NORTH'),
  array('id' => '16','name' => 'Bungoma','subcounty_name' => 'BUNGOMA SOUTH'),
  array('id' => '17','name' => 'Bungoma','subcounty_name' => 'BUNGOMA WEST'),
  array('id' => '18','name' => 'Busia','subcounty_name' => 'BUNYALA'),
  array('id' => '19','name' => 'Kericho','subcounty_name' => 'BURETI'),
  array('id' => '20','name' => 'Busia','subcounty_name' => 'BUSIA'),
  array('id' => '21','name' => 'Kakamega','subcounty_name' => 'BUTERE'),
  array('id' => '22','name' => 'Busia','subcounty_name' => 'BUTULA'),
  array('id' => '23','name' => 'Meru','subcounty_name' => 'Buuri'),
  array('id' => '25','name' => 'Mombasa','subcounty_name' => 'CHANGAMWE'),
  array('id' => '26','name' => 'Bomet','subcounty_name' => 'CHEPALUNGU'),
  array('id' => '27','name' => 'Bungoma','subcounty_name' => 'CHEPTAIS'),
  array('id' => '28','name' => 'Nandi','subcounty_name' => 'CHESUMEI'),
  array('id' => '29','name' => 'Nairobi','subcounty_name' => 'DAGORETTI'),
  array('id' => '30','name' => 'Baringo','subcounty_name' => 'EAST POKOT'),
  array('id' => '31','name' => 'Wajir','subcounty_name' => 'ELDAS'),
  array('id' => '32','name' => 'Nairobi','subcounty_name' => 'EMBAKASI '),
  array('id' => '33','name' => 'Embu','subcounty_name' => 'Embu East'),
  array('id' => '34','name' => 'Embu','subcounty_name' => 'Embu North'),
  array('id' => '35','name' => 'Embu','subcounty_name' => 'Embu West'),
  array('id' => '36','name' => 'Vihiga','subcounty_name' => 'EMUHAYA'),
  array('id' => '37','name' => 'Trans Nzoia','subcounty_name' => 'ENDEBESS'),
  array('id' => '38','name' => 'Kilifi','subcounty_name' => 'GANZE'),
  array('id' => '39','name' => 'Isiolo','subcounty_name' => 'Garbatulla'),
  array('id' => '40','name' => 'Muranga','subcounty_name' => 'GATANGA '),
  array('id' => '41','name' => 'Kiambu','subcounty_name' => 'GATUNDU  SOUTH'),
  array('id' => '42','name' => 'Kiambu','subcounty_name' => 'GATUNDU NORTH'),
  array('id' => '43','name' => 'Siaya','subcounty_name' => 'Gem'),
  array('id' => '44','name' => 'Nakuru','subcounty_name' => 'GILGIL '),
  array('id' => '45','name' => 'Kiambu','subcounty_name' => 'GITHUNGURI'),
  array('id' => '46','name' => 'Kisii','subcounty_name' => 'Gucha'),
  array('id' => '47','name' => 'Kisii','subcounty_name' => 'Gucha South'),
  array('id' => '48','name' => 'Wajir','subcounty_name' => 'HABASWEIN '),
  array('id' => '49','name' => 'Vihiga','subcounty_name' => 'HAMISI '),
  array('id' => '50','name' => 'Homa Bay','subcounty_name' => 'Homabay'),
  array('id' => '51','name' => 'Meru','subcounty_name' => 'Igembe Central'),
  array('id' => '52','name' => 'Meru','subcounty_name' => 'Igembe North'),
  array('id' => '53','name' => 'Meru','subcounty_name' => 'Igembe South'),
  array('id' => '54','name' => 'Kitui','subcounty_name' => 'Ikutha'),
  array('id' => '55','name' => 'Meru','subcounty_name' => 'Imenti South'),
  array('id' => '56','name' => 'Kajiado','subcounty_name' => 'Isinya'),
  array('id' => '57','name' => 'Isiolo','subcounty_name' => 'Isiolo '),
  array('id' => '58','name' => 'Mombasa','subcounty_name' => 'JOMVU'),
  array('id' => '59','name' => 'Kiambu','subcounty_name' => 'JUJA'),
  array('id' => '60','name' => 'Kiambu','subcounty_name' => 'KABETE '),
  array('id' => '61','name' => 'Muranga','subcounty_name' => 'KAHURO'),
  array('id' => '62','name' => 'Kajiado','subcounty_name' => 'Kajiado Central'),
  array('id' => '63','name' => 'Kajiado','subcounty_name' => 'Kajiado North'),
  array('id' => '64','name' => 'Kajiado','subcounty_name' => 'Kajiado West'),
  array('id' => '65','name' => 'Kakamega','subcounty_name' => 'KAKAMEGA CENTRAL'),
  array('id' => '66','name' => 'Kakamega','subcounty_name' => 'KAKAMEGA EAST'),
  array('id' => '67','name' => 'Kakamega','subcounty_name' => 'KAKAMEGA NORTH '),
  array('id' => '68','name' => 'Kakamega','subcounty_name' => 'KAKAMEGA SOUTH'),
  array('id' => '69','name' => 'Mombasa','subcounty_name' => 'KALOLENI'),
  array('id' => '70','name' => 'Nairobi','subcounty_name' => 'Kamukunji'),
  array('id' => '71','name' => 'Muranga','subcounty_name' => 'KANDARA'),
  array('id' => '72','name' => 'Muranga','subcounty_name' => 'KANGEMA'),
  array('id' => '73','name' => 'Machakos','subcounty_name' => 'KANGUNDO'),
  array('id' => '74','name' => 'Uasin Gishu','subcounty_name' => 'KAPSARET'),
  array('id' => '75','name' => 'Nairobi','subcounty_name' => 'KASARANI'),
  array('id' => '76','name' => 'Machakos','subcounty_name' => 'KATHIANI'),
  array('id' => '77','name' => 'Makueni','subcounty_name' => 'Kathonzweni'),
  array('id' => '78','name' => 'Kitui','subcounty_name' => 'Katulani'),
  array('id' => '79','name' => 'Elgeyo-Marakwet','subcounty_name' => 'KEIYO NORTH'),
  array('id' => '80','name' => 'Elgeyo-Marakwet','subcounty_name' => 'KEIYO SOUTH'),
  array('id' => '81','name' => 'Kisii','subcounty_name' => 'Kenyenya'),
  array('id' => '82','name' => 'Kericho','subcounty_name' => 'KERICHO EAST'),
  array('id' => '83','name' => 'Uasin Gishu','subcounty_name' => 'KESSES'),
  array('id' => '84','name' => 'Kakamega','subcounty_name' => 'KHWISERO'),
  array('id' => '85','name' => 'Kiambu','subcounty_name' => 'KIAMBAA '),
  array('id' => '86','name' => 'Kiambu','subcounty_name' => 'KIAMBU '),
  array('id' => '87','name' => 'Turkana','subcounty_name' => 'KIBISH'),
  array('id' => '88','name' => 'Nairobi','subcounty_name' => 'KIBRA'),
  array('id' => '89','name' => 'Makueni','subcounty_name' => 'Kibwezi'),
  array('id' => '91','name' => 'Nyeri','subcounty_name' => 'Kieni West'),
  array('id' => '93','name' => 'Kiambu','subcounty_name' => 'KIKUYU '),
  array('id' => '94','name' => 'Kilifi','subcounty_name' => 'KILIFI NORTH'),
  array('id' => '95','name' => 'Kilifi','subcounty_name' => 'KILIFI SOUTH'),
  array('id' => '96','name' => 'Makueni','subcounty_name' => 'Kilungu'),
  array('id' => '97','name' => 'Bungoma','subcounty_name' => 'KIMILILI  '),
  array('id' => '98','name' => 'Trans Nzoia','subcounty_name' => 'KIMININI'),
  array('id' => '99','name' => 'Kwale','subcounty_name' => 'KINANGO'),
  array('id' => '100','name' => 'Nyandarua','subcounty_name' => 'KINANGOP'),
  array('id' => '101','name' => 'Nyandarua','subcounty_name' => 'KIPIPIRI'),
  array('id' => '102','name' => 'Kericho','subcounty_name' => 'KIPKELION'),
  array('id' => '103','name' => 'West Pokot','subcounty_name' => 'KIPKOMO'),
  array('id' => '104','name' => 'Kirinyaga','subcounty_name' => 'Kirinyaga Central'),
  array('id' => '105','name' => 'Kirinyaga','subcounty_name' => 'Kirinyaga East'),
  array('id' => '106','name' => 'Kirinyaga','subcounty_name' => 'Kirinyaga West'),
  array('id' => '107','name' => 'Kitui','subcounty_name' => 'Kisasi'),
  array('id' => '108','name' => 'Mombasa','subcounty_name' => 'KISAUNI'),
  array('id' => '109','name' => 'Kisii','subcounty_name' => 'Kisii Central'),
  array('id' => '110','name' => 'Kisii','subcounty_name' => 'Kisii South'),
  array('id' => '111','name' => 'Kisumu','subcounty_name' => 'Kisumu Central'),
  array('id' => '112','name' => 'Kisumu','subcounty_name' => 'Kisumu East'),
  array('id' => '113','name' => 'Kisumu','subcounty_name' => 'Kisumu West'),
  array('id' => '114','name' => 'Kitui','subcounty_name' => 'Kitui  Central'),
  array('id' => '115','name' => 'Kitui','subcounty_name' => 'Kitui West'),
  array('id' => '116','name' => 'Kisii','subcounty_name' => 'Kitutu Central'),
  array('id' => '117','name' => 'Baringo','subcounty_name' => 'KOIBATEK'),
  array('id' => '118','name' => 'Bomet','subcounty_name' => 'KONOIN'),
  array('id' => '119','name' => 'Mandera','subcounty_name' => 'Kotulo'),
  array('id' => '120','name' => 'Nakuru','subcounty_name' => 'KURESOI'),
  array('id' => '121','name' => 'Migori','subcounty_name' => 'Kuria East'),
  array('id' => '122','name' => 'Migori','subcounty_name' => 'Kuria West'),
  array('id' => '123','name' => 'Trans Nzoia','subcounty_name' => 'KWANZA'),
  array('id' => '124','name' => 'Kitui','subcounty_name' => 'Kyuso'),
  array('id' => '125','name' => 'Mandera','subcounty_name' => 'Lafey'),
  array('id' => '126','name' => 'Laikipia','subcounty_name' => 'LAIKIPIA CENTRAL'),
  array('id' => '127','name' => 'Laikipia','subcounty_name' => 'LAIKIPIA EAST'),
  array('id' => '128','name' => 'Laikipia','subcounty_name' => 'LAIKIPIA NORTH'),
  array('id' => '129','name' => 'Laikipia','subcounty_name' => 'LAIKIPIA WEST'),
  array('id' => '130','name' => 'Lamu','subcounty_name' => 'LAMU EAST'),
  array('id' => '131','name' => 'Lamu','subcounty_name' => 'LAMU WEST'),
  array('id' => '132','name' => 'Nairobi','subcounty_name' => 'LANGATA'),
  array('id' => '133','name' => 'Kiambu','subcounty_name' => 'LARI'),
  array('id' => '134','name' => 'Mombasa','subcounty_name' => 'LIKONI'),
  array('id' => '135','name' => 'Kakamega','subcounty_name' => 'LIKUYANI '),
  array('id' => '136','name' => 'Kiambu','subcounty_name' => 'LIMURU'),
  array('id' => '137','name' => 'Turkana','subcounty_name' => 'LOIMA'),
  array('id' => '138','name' => 'Kajiado','subcounty_name' => 'Loitoktok'),
  array('id' => '139','name' => 'Kericho','subcounty_name' => 'LONDIANI'),
  array('id' => '140','name' => 'Kitui','subcounty_name' => 'Lower Yatta'),
  array('id' => '141','name' => 'Marsabit','subcounty_name' => 'Loyiangalani'),
  array('id' => '142','name' => 'Vihiga','subcounty_name' => 'LUANDA'),
  array('id' => '143','name' => 'Kakamega','subcounty_name' => 'LUGARI '),
  array('id' => '144','name' => 'Kwale','subcounty_name' => 'LUNGALUNGA'),
  array('id' => '145','name' => 'Tharaka-Nithi','subcounty_name' => 'MAARA'),
  array('id' => '146','name' => 'Machakos','subcounty_name' => 'MACHAKOS'),
  array('id' => '147','name' => 'Kilifi','subcounty_name' => 'MAGARINI'),
  array('id' => '148','name' => 'Nairobi','subcounty_name' => 'MAKADARA '),
  array('id' => '149','name' => 'Makueni','subcounty_name' => 'Makindu'),
  array('id' => '150','name' => 'Makueni','subcounty_name' => 'Makueni'),
  array('id' => '151','name' => 'Kilifi','subcounty_name' => 'MALINDI'),
  array('id' => '152','name' => 'Mandera','subcounty_name' => 'Mandera Central'),
  array('id' => '153','name' => 'Mandera','subcounty_name' => 'Mandera East'),
  array('id' => '154','name' => 'Mandera','subcounty_name' => 'Mandera North'),
  array('id' => '155','name' => 'Mandera','subcounty_name' => 'Mandera West'),
  array('id' => '156','name' => 'Nyamira','subcounty_name' => 'Manga'),
  array('id' => '157','name' => 'Elgeyo-Marakwet','subcounty_name' => 'MARAKWET EAST'),
  array('id' => '158','name' => 'Elgeyo-Marakwet','subcounty_name' => 'MARAKWET WEST'),
  array('id' => '159','name' => 'Kisii','subcounty_name' => 'Marani'),
  array('id' => '160','name' => 'Baringo','subcounty_name' => 'MARIGAT'),
  array('id' => '161','name' => 'Marsabit','subcounty_name' => 'Marsabit Central'),
  array('id' => '162','name' => 'Marsabit','subcounty_name' => 'Marsabit North'),
  array('id' => '163','name' => 'Marsabit','subcounty_name' => 'Marsabit South'),
  array('id' => '164','name' => 'Nyamira','subcounty_name' => 'Masaba North'),
  array('id' => '165','name' => 'Kisii','subcounty_name' => 'Masaba South'),
  array('id' => '166','name' => 'Kajiado','subcounty_name' => 'Mashuru'),
  array('id' => '167','name' => 'Machakos','subcounty_name' => 'MASINGA'),
  array('id' => '168','name' => 'Kakamega','subcounty_name' => 'MATETE'),
  array('id' => '169','name' => 'Nairobi','subcounty_name' => 'MATHARE '),
  array('id' => '170','name' => 'Muranga','subcounty_name' => 'MATHIOYA'),
  array('id' => '171','name' => 'Nyeri','subcounty_name' => 'Mathira East'),
  array('id' => '172','name' => 'Nyeri','subcounty_name' => 'Mathira West'),
  array('id' => '173','name' => 'Kitui','subcounty_name' => 'Matinyani'),
  array('id' => '174','name' => 'Kwale','subcounty_name' => 'MATUGA'),
  array('id' => '175','name' => 'Kakamega','subcounty_name' => 'MATUNGU'),
  array('id' => '176','name' => 'Machakos','subcounty_name' => 'MATUNGULU'),
  array('id' => '177','name' => 'Embu','subcounty_name' => 'Mbeere North'),
  array('id' => '178','name' => 'Embu','subcounty_name' => 'Mbeere South'),
  array('id' => '179','name' => 'Homa Bay','subcounty_name' => 'Mbita'),
  array('id' => '180','name' => 'Makueni','subcounty_name' => 'Mbooni   West'),
  array('id' => '181','name' => 'Makueni','subcounty_name' => 'Mbooni East'),
  array('id' => '182','name' => 'Isiolo','subcounty_name' => 'Merti'),
  array('id' => '183','name' => 'Meru','subcounty_name' => 'Meru Central'),
  array('id' => '184','name' => 'Tharaka-Nithi','subcounty_name' => 'MERU SOUTH'),
  array('id' => '185','name' => 'Nyandarua','subcounty_name' => 'MIRANGINE'),
  array('id' => '186','name' => 'Baringo','subcounty_name' => 'MOGOTIO'),
  array('id' => '187','name' => 'Uasin Gishu','subcounty_name' => 'MOIBEN '),
  array('id' => '188','name' => 'Nakuru','subcounty_name' => 'MOLO'),
  array('id' => '189','name' => 'Mombasa','subcounty_name' => 'MOMBASA'),
  array('id' => '190','name' => 'Marsabit','subcounty_name' => 'Moyale'),
  array('id' => '191','name' => 'Kwale','subcounty_name' => 'MSAMBWENI'),
  array('id' => '192','name' => 'Bungoma','subcounty_name' => 'MT.ELGON'),
  array('id' => '193','name' => 'Kisumu','subcounty_name' => 'Muhoroni'),
  array('id' => '194','name' => 'Makueni','subcounty_name' => 'Mukaa '),
  array('id' => '195','name' => 'Nyeri','subcounty_name' => 'Mukurweini'),
  array('id' => '196','name' => 'Kakamega','subcounty_name' => 'MUMIAS EAST'),
  array('id' => '197','name' => 'Kakamega','subcounty_name' => 'MUMIAS WEST'),
  array('id' => '198','name' => 'Kitui','subcounty_name' => 'Mumoni'),
  array('id' => '199','name' => 'Muranga','subcounty_name' => 'MURANG\'A EAST'),
  array('id' => '200','name' => 'Muranga','subcounty_name' => 'MURANG\'A SOUTH'),
  array('id' => '201','name' => 'Kitui','subcounty_name' => 'Mutitu'),
  array('id' => '202','name' => 'Kitui','subcounty_name' => 'Mutomo'),
  array('id' => '203','name' => 'Machakos','subcounty_name' => 'MWALA'),
  array('id' => '204','name' => 'Taita-Taveta','subcounty_name' => 'MWATATE'),
  array('id' => '205','name' => 'Kirinyaga','subcounty_name' => 'Mwea East'),
  array('id' => '206','name' => 'Kirinyaga','subcounty_name' => 'Mwea West'),
  array('id' => '207','name' => 'Kitui','subcounty_name' => 'Mwingi Central'),
  array('id' => '208','name' => 'Kitui','subcounty_name' => 'Mwingi East '),
  array('id' => '209','name' => 'Kitui','subcounty_name' => 'Mwingi West (Migwani)'),
  array('id' => '210','name' => 'Nakuru','subcounty_name' => 'NAIVASHA'),
  array('id' => '211','name' => 'Nakuru','subcounty_name' => 'NAKURU'),
  array('id' => '212','name' => 'Nakuru','subcounty_name' => 'NAKURU NORTH '),
  array('id' => '213','name' => 'Busia','subcounty_name' => 'NAMBALE'),
  array('id' => '214','name' => 'Nandi','subcounty_name' => 'NANDI CENTRAL '),
  array('id' => '215','name' => 'Nandi','subcounty_name' => 'NANDI EAST '),
  array('id' => '216','name' => 'Nandi','subcounty_name' => 'NANDI NORTH'),
  array('id' => '217','name' => 'Nandi','subcounty_name' => 'NANDI SOUTH '),
  array('id' => '218','name' => 'Narok','subcounty_name' => 'NAROK EAST'),
  array('id' => '219','name' => 'Narok','subcounty_name' => 'NAROK NORTH'),
  array('id' => '220','name' => 'Narok','subcounty_name' => 'NAROK SOUTH'),
  array('id' => '221','name' => 'Narok','subcounty_name' => 'NAROK WEST'),
  array('id' => '222','name' => 'Kakamega','subcounty_name' => 'NAVAKHOLO '),
  array('id' => '223','name' => 'Homa Bay','subcounty_name' => 'Ndhiwa'),
  array('id' => '224','name' => 'Nairobi','subcounty_name' => 'NJIRU'),
  array('id' => '225','name' => 'Nakuru','subcounty_name' => 'NJORO'),
  array('id' => '226','name' => 'Marsabit','subcounty_name' => 'North Horr'),
  array('id' => '227','name' => 'West Pokot','subcounty_name' => 'NORTH POKOT'),
  array('id' => '228','name' => 'Laikipia','subcounty_name' => 'NYAHURURU'),
  array('id' => '229','name' => 'Kisumu','subcounty_name' => 'Nyakach'),
  array('id' => '230','name' => 'Mombasa','subcounty_name' => 'NYALI'),
  array('id' => '231','name' => 'Kisii','subcounty_name' => 'Nyamache'),
  array('id' => '232','name' => 'Nyamira','subcounty_name' => 'Nyamira North'),
  array('id' => '233','name' => 'Nyamira','subcounty_name' => 'Nyamira South'),
  array('id' => '234','name' => 'Nyandarua','subcounty_name' => 'NYANDARUA CENTRAL'),
  array('id' => '235','name' => 'Nyandarua','subcounty_name' => 'NYANDARUA NORTH'),
  array('id' => '236','name' => 'Nyandarua','subcounty_name' => 'NYANDARUA SOUTH'),
  array('id' => '237','name' => 'Nyandarua','subcounty_name' => 'NYANDARUA WEST'),
  array('id' => '238','name' => 'Kisumu','subcounty_name' => 'Nyando'),
  array('id' => '239','name' => 'Migori','subcounty_name' => 'Nyatike'),
  array('id' => '240','name' => 'Nyeri','subcounty_name' => 'Nyeri Central'),
  array('id' => '241','name' => 'Nyeri','subcounty_name' => 'Nyeri South'),
  array('id' => '242','name' => 'Kitui','subcounty_name' => 'Nzambani '),
  array('id' => '243','name' => 'Makueni','subcounty_name' => 'Nzaui'),
  array('id' => '244','name' => 'West Pokot','subcounty_name' => 'POKOT CENTRAL'),
  array('id' => '245','name' => 'West Pokot','subcounty_name' => 'POKOT SOUTH'),
  array('id' => '246','name' => 'Kilifi','subcounty_name' => 'RABAI'),
  array('id' => '247','name' => 'Homa Bay','subcounty_name' => 'Rachuonyo East'),
  array('id' => '248','name' => 'Homa Bay','subcounty_name' => 'Rachuonyo North'),
  array('id' => '249','name' => 'Homa Bay','subcounty_name' => 'Rachuonyo South'),
  array('id' => '250','name' => 'Homa Bay','subcounty_name' => 'Rangwe'),
  array('id' => '251','name' => 'Siaya','subcounty_name' => 'Rarieda'),
  array('id' => '252','name' => 'Nakuru','subcounty_name' => 'RONGAI '),
  array('id' => '253','name' => 'Migori','subcounty_name' => 'Rongo'),
  array('id' => '254','name' => 'Kiambu','subcounty_name' => 'RUIRU'),
  array('id' => '255','name' => 'Vihiga','subcounty_name' => 'SABATIA'),
  array('id' => '256','name' => 'Samburu','subcounty_name' => 'SAMBURU CENTRAL'),
  array('id' => '257','name' => 'Samburu','subcounty_name' => 'SAMBURU EAST'),
  array('id' => '258','name' => 'Samburu','subcounty_name' => 'SAMBURU NORTH'),
  array('id' => '259','name' => 'Kisii','subcounty_name' => 'Sameta'),
  array('id' => '260','name' => 'Busia','subcounty_name' => 'SAMIA'),
  array('id' => '261','name' => 'Kisumu','subcounty_name' => 'Seme'),
  array('id' => '262','name' => 'Siaya','subcounty_name' => 'Siaya'),
  array('id' => '263','name' => 'Kericho','subcounty_name' => 'SIGOWET/SOIN'),
  array('id' => '264','name' => 'Marsabit','subcounty_name' => 'Sololo'),
  array('id' => '265','name' => 'Bomet','subcounty_name' => 'SOTIK'),
  array('id' => '266','name' => 'Uasin Gishu','subcounty_name' => 'SOY '),
  array('id' => '267','name' => 'Nairobi','subcounty_name' => 'STAREHE'),
  array('id' => '268','name' => 'Homa Bay','subcounty_name' => 'Suba'),
  array('id' => '269','name' => 'Nakuru','subcounty_name' => 'SUBUKIA '),
  array('id' => '270','name' => 'Migori','subcounty_name' => 'Suna East'),
  array('id' => '271','name' => 'Migori','subcounty_name' => 'Suna West'),
  array('id' => '272','name' => 'Taita-Taveta','subcounty_name' => 'TAITA'),
  array('id' => '273','name' => 'Tana River','subcounty_name' => 'TANA DELTA'),
  array('id' => '274','name' => 'Tana River','subcounty_name' => 'TANA NORTH'),
  array('id' => '275','name' => 'Tana River','subcounty_name' => 'TANA RIVER'),
  array('id' => '276','name' => 'Wajir','subcounty_name' => 'TARBAJ'),
  array('id' => '277','name' => 'Taita-Taveta','subcounty_name' => 'TAVETA'),
  array('id' => '278','name' => 'Busia','subcounty_name' => 'TESO NORTH'),
  array('id' => '279','name' => 'Busia','subcounty_name' => 'TESO SOUTH'),
  array('id' => '280','name' => 'Nyeri','subcounty_name' => 'Tetu'),
  array('id' => '281','name' => 'Tharaka-Nithi','subcounty_name' => 'THARAKA NORTH'),
  array('id' => '282','name' => 'Tharaka-Nithi','subcounty_name' => 'THARAKA SOUTH'),
  array('id' => '283','name' => 'Kiambu','subcounty_name' => 'THIKA EAST'),
  array('id' => '284','name' => 'Kiambu','subcounty_name' => 'THIKA WEST'),
  array('id' => '285','name' => 'Meru','subcounty_name' => 'Tigania Central '),
  array('id' => '286','name' => 'Meru','subcounty_name' => 'Tigania East'),
  array('id' => '288','name' => 'Nandi','subcounty_name' => 'TINDERET'),
  array('id' => '289','name' => 'Trans Nzoia','subcounty_name' => 'TRANS NZOIA EAST'),
  array('id' => '290','name' => 'Trans Nzoia','subcounty_name' => 'TRANS NZOIA WEST'),
  array('id' => '291','name' => 'Narok','subcounty_name' => 'TRANSMARA EAST'),
  array('id' => '292','name' => 'Narok','subcounty_name' => 'TRANSMARA WEST'),
  array('id' => '293','name' => 'Kitui','subcounty_name' => 'Tseikuru'),
  array('id' => '294','name' => 'Uasin Gishu','subcounty_name' => 'TURBO'),
  array('id' => '295','name' => 'Turkana','subcounty_name' => 'TURKANA CENTRAL'),
  array('id' => '296','name' => 'Turkana','subcounty_name' => 'TURKANA EAST'),
  array('id' => '297','name' => 'Turkana','subcounty_name' => 'TURKANA NORTH'),
  array('id' => '298','name' => 'Turkana','subcounty_name' => 'TURKANA SOUTH'),
  array('id' => '299','name' => 'Turkana','subcounty_name' => 'TURKANA WEST'),

  array('id' => '300','name' => 'Siaya','subcounty_name' => 'Ugenya'),
  array('id' => '301','name' => 'Siaya','subcounty_name' => 'Ugunja'),
  array('id' => '302','name' => 'Migori','subcounty_name' => 'Uriri'),
  array('id' => '304','name' => 'Taita-Taveta','subcounty_name' => 'VOI'),
  array('id' => '305','name' => 'Wajir','subcounty_name' => 'WAJIR EAST'),
  array('id' => '306','name' => 'Wajir','subcounty_name' => 'WAJIR NORTH'),
  array('id' => '307','name' => 'Wajir','subcounty_name' => 'WAJIR SOUTH'),
  array('id' => '308','name' => 'Wajir','subcounty_name' => 'WAJIR WEST'),
  array('id' => '309','name' => 'Bungoma','subcounty_name' => 'WEBUYE WEST'),
  array('id' => '310','name' => 'West Pokot','subcounty_name' => 'WEST POKOT'),
  array('id' => '311','name' => 'Nairobi','subcounty_name' => 'WESTLANDS '),
  array('id' => '312','name' => 'Machakos','subcounty_name' => 'YATTA')
);
    foreach($sub_counties as $resultset)
    {
        $countName=$resultset['name'];
        $subCountyName=$resultset['subcounty_name'];
        $county=County::where(['county_name'=>$countName])->first();
           if($county)
           {
              $model=SubCounty::where(['county_id'=>$county->id,'sub_county_name'=>$subCountyName])->first();
               if(!$model)
               {
              $model=new SubCounty();
              $model->county_id=$county->id;
              $model->sub_county_name=$subCountyName;
              $model->created_by=1;
              $model->save();
             

               }
             
           }


         
    }

    }
}
