version: "3.7"
services:
  app:
    build:
      args:
        user: jimmy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: asdsp
    container_name: asdsp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - asdsp

  db:
    image: mysql:8.0
    container_name: asdsp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - asdsp

  nginx:
    image: nginx:alpine
    container_name: asdsp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - asdsp

networks:
  asdsp:
    driver: bridge