<?php

use Illuminate\Database\Seeder;
use App\Helpers\Helper;
use App\User;
class CountyUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = array(
  array('id' => '9682','name' => 'Hisanya Hillary','email' => 'hilary@geeckoltd.com','username' => 'hilary@geeckoltd.com','phone' => '254708236804','org_id' => '5','county_name' => 'Kiambu','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-09-22 15:18:17','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-09-22 08:21:30'),
  array('id' => '9683','name' => 'John Rutere','email' => 'ruterejohn@gmail.com','username' => 'ruterejohn@gmail.com','phone' => '254722406738','org_id' => '41','county_name' => 'Meru','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-09-22 16:14:53','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-04 07:48:41'),
  array('id' => '9685','name' => 'Victor Namboka','email' => 'victormusebe@gmail.com','username' => 'victormusebe@gmail.com','phone' => '0724855306','org_id' => '27','county_name' => 'West Pokot','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-09-24 16:56:11','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 12:02:53'),
  array('id' => '9689','name' => 'MARSABIT  COUNTY','email' => 'asdspmbt@gmail.com','username' => 'asdspmbt@gmail.com','phone' => '254722859207','org_id' => '39','county_name' => 'Marsabit','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-04 14:54:12','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-04 07:54:37'),
  array('id' => '9690','name' => 'Hamisi Mwakibarua','email' => 'hmwakibarua@gmail.com','username' => 'hmwakibarua@gmail.com','phone' => '254727745546','org_id' => '13','county_name' => 'Mombasa','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-04 18:36:20','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-03 16:49:34'),
  array('id' => '9696','name' => 'Eunice','email' => 'eunicesakong@yahoo.com','username' => 'eunicesakong@yahoo.com','phone' => '254712117520','org_id' => '3','county_name' => 'Machakos','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 15:22:42','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-21 19:18:09'),
  array('id' => '9699','name' => 'Paul Kinoti','email' => 'paulkinoti94@gmail.com','username' => 'paulkinoti94@gmail.com','phone' => '0723265115','org_id' => '41','county_name' => 'Meru','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 15:48:24','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 11:29:16'),
  array('id' => '9700','name' => 'Kabale Somo','email' => 'kabale010@gmail.com','username' => 'kabale010@gmail.com','phone' => '0724498751','org_id' => '39','county_name' => 'Marsabit','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 15:52:43','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 09:05:43'),
  array('id' => '9701','name' => 'Kennedy Ogutu','email' => 'ogutukennedy25@gmail.com','username' => 'ogutukennedy25@gmail.com','phone' => '0726220388','org_id' => '23','county_name' => 'Migori','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 15:54:07','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-18 09:44:02'),
  array('id' => '9702','name' => 'Makanda Chuma Johnstone','email' => 'makmaume@gmail.com','username' => 'makmaume@gmail.com','phone' => '0720679143','org_id' => '18','county_name' => 'Bungoma','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 15:57:19','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 08:58:54'),
  array('id' => '9703','name' => 'Busia County','email' => 'janemroom@gmail.com','username' => 'janemroom@gmail.com','phone' => '0726523674','org_id' => '19','county_name' => 'Busia','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 15:59:24','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 11:56:57'),
  array('id' => '9704','name' => 'Vihiga','email' => 'pkmayende@yahoo.com','username' => 'pkmayende@yahoo.com','phone' => '0725882739','org_id' => '17','county_name' => 'Vihiga','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:01:08','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-22 09:13:22'),
  array('id' => '9706','name' => 'Kisii','email' => 'Ombogo33@gmail.com','username' => 'Ombogo33@gmail.com','phone' => '0722226529','org_id' => '24','county_name' => 'Kisii','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:02:24','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-12-09 11:05:07'),
  array('id' => '9707','name' => 'Ednah Cheptum Songol','email' => 'songolednah@yahoo.com','username' => 'songolednah@yahoo.com','phone' => '0725328028','org_id' => '34','county_name' => 'Baringo','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:02:36','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 09:54:08'),
  array('id' => '9708','name' => 'Paul Muthuo','email' => 'asdspnyandarua@gmail.com','username' => 'asdspnyandarua@gmail.com','phone' => '0725942216','org_id' => '32','county_name' => 'Nyandarua','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:02:50','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-23 10:50:04'),
  array('id' => '9709','name' => 'Muranga','email' => 'jcngubia94@gmail.com','username' => 'jcngubia94@gmail.com','phone' => '0724235801','org_id' => '46','county_name' => 'Muranga','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:04:04','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-23 09:57:21'),
  array('id' => '9710','name' => 'Sangut','email' => 'sangutalex@gmail.com','username' => 'sangutalex@gmail.com','phone' => '0723482701','org_id' => '33','county_name' => 'Samburu','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:05:23','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 09:51:18'),
  array('id' => '9711','name' => 'SIAYA  County','email' => 'stevenoketch@yahoo.com','username' => 'stevenoketch@yahoo.com','phone' => '254712422041','org_id' => '20','county_name' => 'Siaya','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:06:00','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-05 08:30:40'),
  array('id' => '9712','name' => 'Nyamira County','email' => 'zablonoirere@gmail.com','username' => 'zablonoirere@gmail.com','phone' => '0726484812','org_id' => '25','county_name' => 'Nyamira','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:07:26','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-17 11:41:43'),
  array('id' => '9713','name' => 'Laikipia County','email' => 'gladysmugure6@gmail.com','username' => 'gladysmugure6@gmail.com','phone' => '0705172434','org_id' => '47','county_name' => 'Laikipia','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:09:11','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-20 07:13:13'),
  array('id' => '9717','name' => 'Kirinyaga County','email' => 'juliuskomunga@yahoo.com','username' => 'juliuskomunga@yahoo.com','phone' => '0721650412','org_id' => '45','county_name' => 'Kirinyaga','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:11:09','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-26 10:48:36'),
  array('id' => '9718','name' => 'Lochakwan Peter','email' => 'ekuwampeter@gmail.com','username' => 'ekuwampeter@gmail.com','phone' => '0718988718','org_id' => '26','county_name' => 'Turkana','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:11:52','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-12 12:05:03'),
  array('id' => '9720','name' => 'Richard Chelanga','email' => 'richelanga@gmail.com','username' => 'richelanga@gmail.com','phone' => '254725867654','org_id' => '30','county_name' => 'Elgeyo-Marakwet','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:12:52','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 11:31:34'),
  array('id' => '9722','name' => 'Kakamega County','email' => 'amungas65@yahoo.com','username' => 'amungas65@yahoo.com','phone' => '0721675929','org_id' => '16','county_name' => 'Kakamega','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:17:58','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-03 12:59:43'),
  array('id' => '9725','name' => 'Tharaka-Nithi','email' => 'jothammugendi71@gmail.com','username' => 'jothammugendi71@gmail.com','phone' => '0723887739','org_id' => '42','county_name' => 'Tharaka-Nithi','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 16:21:53','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-29 08:08:16'),
  array('id' => '9772','name' => 'Kitui County','email' => 'laurynwabz1@gmail.com','username' => 'laurynwabz1@gmail.com','phone' => '0791343886','org_id' => '2','county_name' => 'Kitui','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-13 17:07:19','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-13 10:08:59'),
  array('id' => '9778','name' => 'Amos Chelule','email' => 'camooke@yahoo.com','username' => 'camooke@yahoo.com','phone' => '0720871425','org_id' => '38','county_name' => 'Bomet','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:28:14','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-15 06:51:24'),
  array('id' => '9779','name' => 'Pauline Murithi','email' => 'opgemurithi@gmail.com','username' => 'opgemurithi@gmail.com','phone' => '254722497762','org_id' => '43','county_name' => 'Embu','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:29:26','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-16 11:53:01'),
  array('id' => '9780','name' => 'Pius Kitili Mang\'ee','email' => 'piusk40@gmail.com','username' => 'piusk40@gmail.com','phone' => '254720787055','org_id' => '10','county_name' => 'Garissa','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:30:42','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-14 11:54:16'),
  array('id' => '9781','name' => 'Lawrence Karani Kinoti','email' => 'Lawrencekinoti5@gmail.com','username' => 'Lawrencekinoti5@gmail.com','phone' => '254728816053','org_id' => '40','county_name' => 'Isiolo','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:31:42','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-09 09:15:20'),
  array('id' => '9782','name' => 'Hillary Chege','email' => 'chegeh78@gmail.com','username' => 'chegeh78@gmail.com','phone' => '254720277910','org_id' => '6','county_name' => 'Kajiado','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:32:43','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-29 11:34:39'),
  array('id' => '9783','name' => 'Benard Too','email' => 'benaktoo@gmail.com','username' => 'benaktoo@gmail.com','phone' => '254722468894','org_id' => '37','county_name' => 'Kericho','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:33:31','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-22 07:25:29'),
  array('id' => '9784','name' => 'Ngugi Ticha','email' => 'ngugiticha@yahoo.com','username' => 'ngugiticha@yahoo.com','phone' => '254722670211','org_id' => '7','county_name' => 'Kilifi','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:34:33','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-15 07:05:46'),
  array('id' => '9785','name' => 'Harrison Okello','email' => 'harryokello@yahoo.com','username' => 'harryokello@yahoo.com','phone' => '254722465075','org_id' => '21','county_name' => 'Kisumu','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 15:35:35','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-15 10:41:42'),
  array('id' => '9786','name' => 'Said Sudi Mchombo','email' => 'saidsudi41@gmail.com','username' => 'saidsudi41@gmail.com','phone' => '254703146603','org_id' => '14','county_name' => 'Kwale','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:16:45','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-15 06:49:52'),
  array('id' => '9787','name' => 'Beth Mwaringa','email' => 'bmwaringa015@gmail.com','username' => 'bmwaringa015@gmail.com','phone' => '254727782601','org_id' => '9','county_name' => 'Lamu','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:18:21','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-15 06:49:50'),
  array('id' => '9788','name' => 'Jackson Katua','email' => 'jacksonkatua36@gmail.com','username' => 'jacksonkatua36@gmail.com','phone' => '254721405998','org_id' => '4','county_name' => 'Makueni','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:19:26','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-24 08:50:14'),
  array('id' => '9789','name' => 'John  M. Mutinda','email' => 'Jmutinda85@yahoo.com','username' => 'Jmutinda85@yahoo.com','phone' => '264729069571','org_id' => '12','county_name' => 'Mandera','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:20:27','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-25 11:12:50'),
  array('id' => '9790','name' => 'Lorainne Mlamba','email' => 'wamlash@yahoo.com','username' => 'wamlash@yahoo.com','phone' => '254720597193','org_id' => '13','county_name' => 'Mombasa','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:21:37','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => NULL),
  array('id' => '9791','name' => 'David Kyalo','email' => 'davidkyalo@gmail.com','username' => 'davidkyalo@gmail.com','phone' => '254721558080','org_id' => '1','county_name' => 'Nairobi','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:23:31','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-14 11:42:14'),
  array('id' => '9792','name' => 'Florence Mukesia Wanjala','email' => 'mukflora@gmail.com','username' => 'mukflora@gmail.com','phone' => '254710394370','org_id' => '35','county_name' => 'Nakuru','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:24:29','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-05 11:05:22'),
  array('id' => '9793','name' => 'Viola Rotich','email' => 'rovioleti@yahoo.com','username' => 'rovioleti@yahoo.com','phone' => '254721930588','org_id' => '31','county_name' => 'Nandi','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:25:20','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-22 07:30:47'),
  array('id' => '9794','name' => 'Peninah Mutuota','email' => 'peninahnyokabi9@gmail.com','username' => 'peninahnyokabi9@gmail.com','phone' => '254729152291','org_id' => '36','county_name' => 'Narok','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:27:07','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-14 11:54:47'),
  array('id' => '9795','name' => 'Editar Njeru','email' => 'editarnjeru@gmail.com','username' => 'editarnjeru@gmail.com','phone' => '254796015346','org_id' => '44','county_name' => 'Nyeri','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:28:08','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-14 13:17:37'),
  array('id' => '9796','name' => 'Wawire Edwin','email' => 'ek.wawire@gmail.com','username' => 'ek.wawire@gmail.com','phone' => '254725154218','org_id' => '15','county_name' => 'Taita-Taveta','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:29:28','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-15 06:53:08'),
  array('id' => '9797','name' => 'Boaz Shiramba','email' => 'boazshiramba@yahoo.com','username' => 'boazshiramba@yahoo.com','phone' => '254723789487','org_id' => '8','county_name' => 'Tana River','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:31:50','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-14 11:56:25'),
  array('id' => '9798','name' => 'Catherine Wekunda','email' => 'katherinewekunda@gmail.com','username' => 'katherinewekunda@gmail.com','phone' => '254721609211','org_id' => '28','county_name' => 'Trans Nzoia','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:32:41','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-17 11:15:23'),
  array('id' => '9799','name' => 'Kibias Edwin','email' => 'kibiasedwin@gmail.com','username' => 'kibiasedwin@gmail.com','phone' => '254722668868','org_id' => '29','county_name' => 'Uasin Gishu','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 16:33:55','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-11-26 14:05:13'),
  array('id' => '9800','name' => 'Wajir County','email' => 'askilonzo.as1@gmail.com','username' => 'askilonzo.as1@gmail.com','phone' => '254722553311','org_id' => '11','county_name' => 'Wajir','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 18:58:13','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-10-15 05:25:16'),
  array('id' => '9801','name' => 'Kiambu	Jane Njue','email' => 'janpato50@gmail.com','username' => 'janpato50@gmail.com','phone' => '254724232305','org_id' => '5','county_name' => 'Kiambu','user_type' => 'Internal','user_status' => 'Active','id_number' => NULL,'gender' => NULL,'county' => NULL,'country' => 'Kenya','created_at' => '2021-10-14 19:00:39','user_role' => 'County Co-ordinator','personal_number' => NULL,'lastlogindate' => '2021-12-13 15:36:05')
);
 



foreach($users as $key)
      {
      	  
      	DB::beginTransaction();
      	
      	$user= DB::table('users')->insert([
            'name' =>$key['name'] ,
            'email'=>$key['email'],
            'username'=>$key['username'],
            'password'=>bcrypt('123456'),
            'phone'=>$key['phone'],
            'user_type'=>'Internal',
            'verification_code'=>Helper::generatePin(12),
            'org_id'=>$key['org_id'],
             'created_at'=>date('Y-m-d H:i:s'),
             'updated_at'=>date('Y-m-d H:i:s'),
             'confirmed_at'=>date('Y-m-d H:i:s'),
             'lastlogindate'=>$key['lastlogindate'],
            ]);
      	      $user=User::latest('id')->first();
      	    DB::table('profiles')->insert([
            'user_id' => $user->id,
            'created_at'=>date('Y-m-d H:i:s'),
            'updated_at'=>date('Y-m-d H:i:s'),
           ]);
          $user->assignRole('County Co-ordinator');
          DB::commit();
      }





    }
}
